name: tiktok-downloader
services:
  - name: api
    source_dir: backend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
      port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8000"
      - key: ENV
        value: "production"
      - key: API_SECRET_KEY
        type: SECRET
        value: "your-secret-key-here"
      - key: JWT_SECRET_KEY
        type: SECRET
        value: "your-jwt-secret-here"
      - key: ADMIN_API_KEY
        type: SECRET
        value: "your-admin-key-here"
      - key: MAX_DOWNLOADS
        value: "50"
      - key: MAX_CONCURRENT_DOWNLOADS
        value: "10"
      - key: VERIFY_SSL
        value: "true"

  - name: web
    source_dir: frontend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
      - key: NEXT_PUBLIC_API_URL
        value: "${_self.APP_URL}/api/v1"
      - key: NEXT_PUBLIC_SITE_URL
        value: "${_self.APP_URL}"
