name: tiktok-downloader
services:
  - name: backend
    dockerfile_path: app/api/Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
      port: 8001
    instance_count: 1
    instance_size_slug: basic-s
    envs:
      # Environment
      - key: PORT
        value: "8001"
      - key: ENV
        value: "production"
      - key: DEBUG
        value: "false"

      # Security Keys (as secrets)
      - key: API_SECRET_KEY
        type: SECRET
        scope: RUN_TIME
      - key: JWT_SECRET_KEY
        type: SECRET
        scope: RUN_TIME
      - key: WEBSITE_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: ADMIN_API_KEY
        type: SECRET
        scope: RUN_TIME

      # API Security
      - key: API_KEY_HEADER_NAME
        value: "X-API-Key"
      - key: REQUIRE_API_KEY
        value: "true"

      # Download Settings
      - key: DOWNLOAD_FOLDER
        value: "/app/downloads"
      - key: MAX_DOWNLOADS
        value: "50"
      - key: MAX_CONCURRENT_DOWNLOADS
        value: "10"
      - key: DOWNLOAD_EXPIRY_MINUTES
        value: "60"
      - key: VERIFY_SSL
        value: "true"

      # Rate Limiting
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"

      # CORS Settings
      - key: ALLOWED_ORIGINS
        value: "https://tiktokwatermarkremover.com,https://www.tiktokwatermarkremover.com"

  - name: frontend
    dockerfile_path: app/web/Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: "production"
      - key: NEXT_PUBLIC_API_URL
        value: "${_self.HOSTNAME}/api/v1"
      - key: NEXT_PUBLIC_WEBSITE_API_KEY
        scope: RUN_TIME
        value: "${WEBSITE_API_KEY}"

routes:
  - path: /api
    service: backend
    preserve_path_prefix: true
  - path: /health
    service: backend
    preserve_path_prefix: false
  - path: /docs
    service: backend
    preserve_path_prefix: false
  - path: /openapi.json
    service: backend
    preserve_path_prefix: false
  - path: /
    service: frontend
    preserve_path_prefix: false
