name: tiktok-downloader
services:
  - name: web
    dockerfile_path: Dockerfile # Using our combined Dockerfile
    source_dir: . # Root directory
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
      port: 8000
      initial_delay_seconds: 30
    instance_count: 1
    instance_size_slug: basic-s
    envs:
      # Environment
      - key: PORT
        value: "8000"
      - key: ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: NODE_ENV
        value: "production"

      # Security Keys (as secrets)
      - key: API_SECRET_KEY
        type: SECRET
        scope: RUN_TIME
      - key: JWT_SECRET_KEY
        type: SECRET
        scope: RUN_TIME
      - key: WEBSITE_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: ADMIN_API_KEY
        type: SECRET
        scope: RUN_TIME

      # API Security
      - key: API_KEY_HEADER_NAME
        value: "X-API-Key"
      - key: REQUIRE_API_KEY
        value: "true"

      # Download Settings
      - key: DOWNLOAD_FOLDER
        value: "/app/downloads"
      - key: MAX_DOWNLOADS
        value: "50"
      - key: MAX_CONCURRENT_DOWNLOADS
        value: "10"
      - key: DOWNLOAD_EXPIRY_MINUTES
        value: "60"
      - key: VERIFY_SSL
        value: "true"

      # Rate Limiting
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"

      # Frontend Settings
      - key: NEXT_PUBLIC_API_URL
        value: "/api/v1"
      - key: NEXT_PUBLIC_WEBSITE_API_KEY
        scope: RUN_TIME
        value: "${WEBSITE_API_KEY}"

routes:
  - path: /api
    component: api
    preserve_path_prefix: true
  - path: /health
    component: api
    preserve_path_prefix: false
  - path: /docs
    component: api
    preserve_path_prefix: false
  - path: /openapi.json
    component: api
    preserve_path_prefix: false
  - path: /
    component: web
    preserve_path_prefix: false
