name: tiktok-downloader
region: nyc

services:
  - name: api
    github:
      repo: CLOVETHEDESTROYER/TikTokDownloader
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8001
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
    routes:
      - path: /
    envs:
      - key: ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: REQUIRE_API_KEY
        value: "false"
