name: tiktok-downloader

# Region - New York
region: nyc

# Backend Service
services:
  - name: backend
    github:
      repo: CLOVETHEDESTROYER/TikTokDownloader
      branch: main
      deploy_on_push: true
    dockerfile_path: app/api/Dockerfile
    http_port: 8001
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
    envs:
      - key: ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8001"
      - key: HOST
        value: "0.0.0.0"
      - key: PYTHONPATH
        value: /app
      - key: REQUIRE_API_KEY
        value: "false"
      - key: FRONTEND_URL
        value: ${APP_URL}
      - key: API_SECRET_KEY
        type: SECRET
        value: REPLACE_WITH_YOUR_SECRET
      - key: WEBSITE_API_KEY
        type: SECRET
        value: REPLACE_WITH_YOUR_KEY
      - key: ADMIN_API_KEY
        type: SECRET
        value: REPLACE_WITH_YOUR_ADMIN_KEY
    routes:
      - path: /api
      - path: /health
      - path: /downloads

  - name: frontend
    github:
      repo: CLOVETHEDESTROYER/TikTokDownloader
      branch: main
      deploy_on_push: true
    dockerfile_path: app/web/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm run build
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_API_URL
        value: ${APP_URL}/api/v1
      - key: NEXT_PUBLIC_WEBSITE_API_KEY
        type: SECRET
        value: REPLACE_WITH_YOUR_KEY
    routes:
      - path: /

# Domain configuration (optional - add after initial deployment)
# domains:
#   - domain: tiktokwatermarkremover.com
#     type: PRIMARY
#   - domain: www.tiktokwatermarkremover.com
#     type: ALIAS
