name: tiktok-downloader
services:
  - name: api
    source_dir: backend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
      port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8000"
      - key: ENV
        value: "production"
      - key: API_SECRET_KEY
        type: SECRET
      - key: JWT_SECRET_KEY
        type: SECRET
      - key: ADMIN_API_KEY
        type: SECRET
      - key: WEBSITE_API_KEY
        type: SECRET
      - key: API_KEY_HEADER_NAME
        value: "X-API-Key"
      - key: REQUIRE_API_KEY
        value: "false"
      - key: MAX_DOWNLOADS
        value: "50"
      - key: MAX_CONCURRENT_DOWNLOADS
        value: "10"
      - key: VERIFY_SSL
        value: "true"
      - key: DOWNLOAD_FOLDER
        value: "/var/www/downloads"
      - key: DOWNLOAD_EXPIRY_HOURS
        value: "24"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      # CORS settings
      - key: FRONTEND_URL
        value: "${_self.PUBLIC_URL}"
      - key: CORS_ALLOW_METHODS
        value: '["GET","POST","PUT","DELETE","OPTIONS"]'
      - key: CORS_ALLOW_HEADERS
        value: "Content-Type,Authorization,X-Request-ID,X-API-Key,Accept,Origin,Cache-Control"
      - key: ADDITIONAL_ALLOWED_ORIGINS
        value: "https://tiktokwatermarkremover.com,https://www.tiktokwatermarkremover.com"
      - key: CORS_MAX_AGE
        value: "3600"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"

  - name: web
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    run_command: ./start.sh
    health_check:
      http_path: /health
      port: 3000
      initial_delay_seconds: 30
    instance_count: 1
    instance_size_slug: basic-s
    envs:
      # Frontend Environment Variables
      - key: NODE_ENV
        value: "production"
      - key: NEXT_PUBLIC_API_URL
        value: "/api/v1"
      - key: NEXT_PUBLIC_SITE_URL
        value: "${_self.PUBLIC_URL}"
      - key: NEXT_PUBLIC_WEBSITE_API_KEY
        scope: RUN_TIME
        value: "${WEBSITE_API_KEY}"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    http_port: 3000

routes:
  - path: /api
    component: api
    preserve_path_prefix: true
  - path: /health
    component: api
    preserve_path_prefix: false
  - path: /docs
    component: api
    preserve_path_prefix: false
  - path: /openapi.json
    component: api
    preserve_path_prefix: false
  - path: /
    component: web
    preserve_path_prefix: false
